### ISSUE TITLE
Add a configuration option to ignore unreachable hosts

### ISSUE THREAD

**Issue by q2dg** [ansible-community/ara#143]
Hello.

Currently Ara shows a failed status icon when a host is unreachable. This is a valid behaviour in a datacenter because an unreachable host could be a great problem there but in our humble intermediate school this behaviour is a little verbose because our student's hosts appear as unreachable simply because they are stopped.

Could be possible to add a (boolean) configuration option to Ara to let the admin specify if he/she wants a playbook to be marked as failed (as it is now) or not (our wanted behaviour) when that playbook tried to run on a unreachable host? Obviously, if the playbook ran on a reachable host but wiih the result of a failed task, it should always been marked as failed unconditionally.

Thanks a lot!

**Comment by dmsimard** [comment]
Hi @q2dg,

I think it's a very valid use case to want to ignore unreachable hosts, thanks for the issue!

I'm not sure what's the right approach to provide the functionality yet and I need to think a little bit about it. It's a bit messy :)

Currently this logic is handled naively by the callback plugin here:
https://github.com/ansible-community/ara/blob/c60d8b194dc54f456f69c93f63308b7c4f01180c/ara/plugins/callback/ara_default.py#L335-L344

Adding a boolean configuration toggle means adding it for the callback so the code above ignores unreachable things. This will make it so the state of the playbook will be "completed", one of the available statuses:
https://github.com/ansible-community/ara/blob/c60d8b194dc54f456f69c93f63308b7c4f01180c/ara/api/models.py#L85-L90

Then the frontend has it's own interpretation based on that:
https://github.com/ansible-community/ara/blob/c60d8b194dc54f456f69c93f63308b7c4f01180c/ara/ui/templates/partials/playbook_status_icon.html#L1-L17

I think it'd be misleading for ara to say that a playbook completed successfully if it had unreachable task results. This means we'd need a way to highlight that there were no failed tasks but there were unreachable hosts.

If we handle this without changing the API, it means the business logic must live in the UI.
The current API call for playbook list isn't comprehensive enough to provide that information but it's in the playbook details -- it's how we print the host stats in the UI.

This feel clunky and improving the API feels like a better fit.
The current problem is that finding out if a playbook has a host which has an unreachable task is expensive because it is nested in the host stats.

One option could be to bubble this information up to the playbook level by adding a new status which would stand for "completed successfully (number of failed tasks: 0) but with unreachable hosts".
Then, the callback logic becomes:

```
status = "unknown"
if len(stats.failures) >= 1:
    status = "failed"
elif len(stats.dark) >= 1:
    status = "completed_with_unreachable"
else:
    status = "completed"
```

This could also be interpreted client side easily by the UI.

We can bikeshed on the name of this new status but the implementation wouldn't require a new boolean.

**Comment by dmsimard** [comment]
@q2dg o/ I'm here with an update.

It's not exactly what you asked for but I thought it might help :)

I've landed an API change that allows to filter host results based on their stats -- including "unreachable": https://github.com/ansible-community/ara/commit/2827d43ac458cf0ae0582761e92fdce31f21577a

I don't have anything on the frontend side of things yet but I've done an implementation of it in the CLI that might interest you:
![Screenshot from 2020-07-22 23-01-05](https://user-images.githubusercontent.com/1291204/88248539-856a6500-cc6f-11ea-9fcf-e674210503f2.png)

What you are looking at is basically the same data that comes up in the reporting interface when looking at a (single) playbook report, ex:
![Screenshot from 2020-07-22 23-05-03](https://user-images.githubusercontent.com/1291204/88248622-d37f6880-cc6f-11ea-8a9e-616e44d17afc.png)

If you want to try it out, it's already merged in the master branch of the repository and there is documentation available here: https://ara.readthedocs.io/en/latest/cli.html#ara-host-list

I'll definitely be looking for feedback and will be tagging a beta before this releases.

**Comment by q2dg** [comment]
Sure!!! I'll try this next days and I'll give you feedback soon!
Thanks a lot for your time and kindness!!

**Comment by q2dg** [comment]
Yeah, I've tried and it's really great!!
THANKS THANKS THANKS A LOT!!!
I'll close the issue if you don't mind

**Comment by dmsimard** [comment]
@q2dg Thanks for you feedback, it's appreciated :) Closing the issue is fine.

I've also just sent a patch to add support for ``--resolve`` which provides an identifier for the playbook in addition to the id:
![Screenshot from 2020-08-31 18-56-57](https://user-images.githubusercontent.com/1291204/91776704-ec0e6700-ebbb-11ea-9248-81c35ad171a0.png)
