### ISSUE TITLE
ara-manage prune doesn't delete all jobs that should be deleted

### ISSUE THREAD

**Issue by arrfab** [ansible-community/ara#166]
## What is the issue ?
When launching `ara-manage --confirm --days 3` ,  ara only delete 100 playbooks while there are much more to be delete that matches the criteria

## What should be happening ?
It should delete all jobs/playbooks in DB that matches the criteria, but it seems that for "prune" operaion, it also obeys this setting from settings.yml : 

```
PAGE_SIZE: 100
```
Launching it again with that parameter modified to 200 confirms this : 

```
2020-08-26 14:49:01,114 INFO ara.api.management.commands.prune: 200 playbooks deleted

```

While I understand the need for a limit for pagination, it shouldn't apply for a batch operation like pruning old jobs from DB, as actually that means running the same ara-manage prune job multiple times (or switch the PAGE_SIZE limit to insane high number) to delete/prune all jobs matching criteria.

**Comment by dmsimard** [comment]
Hey @arrfab, thanks for the issue :+1: 

The API clients unfortunately don't natively support pagination yet (i.e, continually yield results for each page) but they do support the ``--limit`` argument which has precedence on the pagination settings so you could, for example, have something like:
``ara playbook prune --confirm --days 3 --limit 1000`` and it would work.

I think that's a good compromise for the time being especially because it's a trivial change and can be delivered for 1.5.

By the way, ``ara-manage prune`` will be deprecated in favor of ``ara playbook prune`` in 1.5. It'll be removed in 1.6.

**Comment by arrfab** [comment]
Thanks .. as 'ara' itself isn't included in the container, and that --limit isn't parsed by ara-manage, I guess I'll have to wait for 1.5 and a refreshed container with 'ara' cli added ;-)

**Comment by dmsimard** [comment]
> Thanks .. as 'ara' itself isn't included in the container, and that --limit isn't parsed by ara-manage, I guess I'll have to wait for 1.5 and a refreshed container with 'ara' cli added ;-)

Yup, that's accurate. Soon!

**Comment by dmsimard** [comment]
I have a patch up for review: https://review.opendev.org/#/c/748549/

As a bonus, I've also ported other search parameters from ``ara playbook list`` as I think it could be useful:
![Screenshot from 2020-08-27 19-55-18](https://user-images.githubusercontent.com/1291204/91506089-4303fb80-e89f-11ea-9aad-b92dc01ea6ee.png)
