### ISSUE TITLE
Handlers are missing is ara results

### ISSUE THREAD

**Issue by noonedeadpunk** [ansible-community/ara#178]
## What is the issue ?

Handler execution is missing from ara results. For example [1] seems to fail on `Wait for cluster ready state` task, but in fact it fails on handlers execution [2]. Looking through other tasks, I've noticed that all handlers are not displayed in ara results.

Include relevant information to help the community help you:
- ara[server]-1.5.1
- python3.6, 3.8
- ansible 2.9.9
- centos, ubuntu

[1] https://storage.gra.cloud.ovh.net/v1/AUTH_dcaab5e32b234d56b626f72581e3644c/zuul_opendev_logs_b66/742105/5/check/openstack-ansible-functional-centos-8/b66b199/logs/ara-report/playbooks/1.html#results
[2] https://zuul.opendev.org/t/openstack/build/b66b199b9f7145d2b3025686f98b5ac5/log/job-output.txt#5216

## What should be happening ?

Handler tasks should be displayed in ara results

**Comment by dmsimard** [comment]
Hi @noonedeadpunk and thanks for the issue.

I've made tasks searchable with the handler attribute in a [new patch](https://review.opendev.org/#/c/754405/) and confirmed we indeed have no tasks with ``handler:true`` at all right now: https://api.demo.recordsansible.org/api/v1/tasks?handler=true

I would guess that it's because ara doesn't currently use the ``v2_playbook_on_handler_task_start`` callback hook:
https://github.com/ansible/ansible/blob/ece0be30ab94b3b25f70f3f71f41284a1b990e24/lib/ansible/plugins/callback/__init__.py#L388

Would very much like to fix that. I'll test the hook when I have a chance and ensure we have handler tasks covered.

**Comment by dmsimard** [comment]
I've sent a patch so we can use ``v2_playbook_on_handler_task_start``: https://review.opendev.org/755425

It'll be in master soon and included in a dot release in the near future.
