### ISSUE TITLE
ansible-pull support ?

### ISSUE THREAD

**Issue by eoli3n** [ansible-community/ara#193]
I configure 800 hosts with a 400 tasks playbook, so i'm using ansible-pull script : https://docs.ansible.com/ansible/latest/cli/ansible-pull.html

I can configure ara callback plugin to send logs through http, but in live demo i can not found any field to filter "source" host.
Will you implement ability to see and query host log source ?

**Comment by dmsimard** [comment]
Hi @eoli3n !

ara should "just work" with ansible-pull but let us know if you encounter any issues.

There is no equivalent implementation in the web frontend yet but filtering by host is supported by the API (i.e, https://api.demo.recordsansible.org/api/v1/hosts?name=localhost) as well as the CLI:
![Screenshot from 2020-12-03 09-58-48](https://user-images.githubusercontent.com/1291204/101045286-2b977700-354e-11eb-8dbc-cebd9f36ed2e.png)

There is a WIP patch to implement a "host index" (as opposed to the current playbook index) that I have not had the chance to complete: https://review.opendev.org/c/recordsansible/ara/+/682778

**Comment by eoli3n** [comment]
Thanks

It would be great if ara could handle natively source host, it would answer to 2 cases:
- ansible-pull, every hosts will send logs as
  source: hostname
  playbook hosts: localhost
- multiple ansible server will send logs as
  source: server hostname
  playbook hosts: pattern

An extra filter in ``playbooks`` web ui view could do that.


As we said on IRC, I will try to use labels to filter source hosts as a first workaround, with extra-vars pass to ansible-pull:
```
ansible-pull [...] -e "ara_playbook_labels='source_host:$(hostname -f)'"
```

**Comment by dmsimard** [comment]
Yes, that's a good idea :+1: 

I have a WIP patch that works for saving the controller hostname here: https://review.opendev.org/c/recordsansible/ara/+/765434

Feel free to review and try it out in a virtualenv or something like that:
```
git clone https://github.com/ansible-community/ara
cd ara
git fetch "https://review.opendev.org/recordsansible/ara" refs/changes/34/765434/1 && git checkout FETCH_HEAD
pip install .[server]
# it adds sql migrations that are run automatically by the callback, otherwise:
ara-manage migrate
```

Then run the playbook with the callback enabled and you'll find something like this:
![Screenshot from 2020-12-03 23-51-45](https://user-images.githubusercontent.com/1291204/101123326-9bdfe000-35c2-11eb-9e98-819cbed3b5f6.png)

Mine is localhost because I'm funny and my laptop's FQDN is "localhost" but it should work if you have a real hostname :)

Searching by controller works so you can do ``/api/v1/playbooks?controller=hostname`` and we can add support for it in the CLI too. Need to add a search field in the UI for it as well.

**Comment by eoli3n** [comment]
My user is "user" so i guess we are the same kind :clown_face: 
I test it soon !

**Comment by dmsimard** [comment]
Updated the patch to include tests, the CLI and the UI search implementation:
![Screenshot from 2020-12-04 10-06-30](https://user-images.githubusercontent.com/1291204/101179656-85647380-3618-11eb-8c2e-ad2a7abfc23a.png)

**Comment by dmsimard** [comment]
This will land in 1.5.4 that I am preparing for release early next week.
