### ISSUE TITLE
No module named 'ara'

### ISSUE THREAD

**Issue by scorpio2k2** [ansible-community/ara#272]
Hello,

I tried to install it on an OSX as described in https://ara.readthedocs.io/en/latest/getting-started.html#installing-from-distribution-packages

When I try to execute a playbook it complains about ara module.

[WARNING]: Skipping plugin (/usr/local/lib/python3.9/site-packages/ara/plugins/callback/ara_default.py) as it seems to be invalid: No module named 'ara'

❯ python3 -V
Python 3.9.4

❯ ansible --version
ansible 2.10.8
config file = /Users/xxxxx/.ansible.cfg
configured module search path = ['/Users/xxxxxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/local/Cellar/ansible/3.3.0/libexec/lib/python3.9/site-packages/ansible
executable location = /usr/local/bin/ansible
python version = 3.9.4 (default, Apr 5 2021, 01:50:46) [Clang 12.0.0 (clang-1200.0.32.29)]

**Comment by dmsimard** [comment]
@scorpio2k2 going by the output you provided, it looks like Ansible is installed via brew (under ``/usr/local/Cellar``) whereas ara was installed via pip (under ``/usr/local/lib``).

Both Ansible and ara must be installed under the same python interpreter library for it to work.

There's different ways to go about this, for example you could install both ansible and ara with ``pip install --user`` so that they both end up in ``~/.local/bin`` and ``~/.local/lib`` (or something along these lines, not sure about OSX)

**Comment by scorpio2k2** [comment]
Works after installing ansible with pip.  

Thanks!
