### ISSUE TITLE
Thoughts and ideas about host index page improvements

### ISSUE THREAD

**Issue by hille721** [ansible-community/ara#331]
Hi @dmsimard,

after some weeks/months with the new host index page view, here my thoughts and ideas for improvements:

## thoughts
* the playbook status icon is to prominent in column one. I'm always confused if I see there a red icon, but the host was running green. Also there is the question if we anyhow need this column a the host view.
* same thing about playbook duration. On the host view I'm not really intertested to see this. Imo we should highlight more host specific thins instead
* playbook name is missing. You have to click on the report of one host, to see which playbook it is
* "Last update" and "Last results" are misleading column tiles if "Include all playbook reports" is ticked

## ideas
* reordering of the columns, imo the hostname and last result columns should be highlighted more prominent, eg, by putting them into the beginning
* adding playbook name/path to the view
* dropping playbook status and playbook duration column
* addinng possibility to filer for playbook name/path and subset
* filtering for host facts
* renaming "Last update" and "Last results" to "Update"/"Results"
* adding ansible groups to the view (there I have no idea, if this is technical possible, I think currently the groups in which a host is, is not reported?), but it would be an awesome feature

**Comment by hille721** [comment]
the idea of host fact searching and filtering is also already tracked in #297

**Comment by dmsimard** [comment]
Hey @hille721, thanks for the feedback <3

I need to focus on AnsibleFest and Contributor Summit things for now, let me get back to you with my thoughts when I have a chance.

**Comment by hille721** [comment]
@dmsimard, finally I had some time to look into this and did some changes how I would love too see the host index page:

![image](https://user-images.githubusercontent.com/38468371/182858248-e7501c5b-738d-4b36-8bfc-ae253a6dae3c.png)

* removed playbook status and playbook duration columns
* added playbook name / path and make it searchable (in fact the search is just for the playbook id, not the playbook name. Could be improved)

Addding playbook name / path is btw really easy with `host.playbook.name` / `host.playbook.path`. I would wish to add at least this column to the next release, because this is really missing (also feedbacked by others in my company).

**Comment by dmsimard** [comment]
@hille721 thanks for working on this. Here's some thoughts.

I think I can concede that the playbook status is not immediately relevant and can even be confusing relative to the status of the tasks that the host ran but I'd keep the playbook duration. It's useful to be able to see how long playbooks with that host took.

I wonder about the order of the columns, especially when comparing the playbook page, the hosts page and the new tasks page.
For easy comparison:

---

# Playbooks
![Selection_015](https://user-images.githubusercontent.com/1291204/182976132-2e5278cd-5078-4884-b5ff-339a7f94e2d2.png)

# Hosts
![Selection_016](https://user-images.githubusercontent.com/1291204/182976137-b0422d5e-bcd0-471f-bf86-59a9af1ea34a.png)

# Tasks (WIP)
![Selection_017](https://user-images.githubusercontent.com/1291204/182976140-024c317a-da0f-4885-921a-c010c2949abe.png)

---

I'm no UI/UX expert and the UI has grown organically over time... When I designed the tables, I like to think I more or less followed this approach:
- Highly variable width columns (such as playbook labels and host facts) should be at the right hand side to avoid needless whitespace in the middle of the tables
- Fixed width columns (such as status, link to report, date, duration) should be on the left hand side so these columns are well aligned and make the best possible use of limited width space
- The name of the thing related to the row should be the first non-fixed width column to make it easy to scan (this is one of the things users will look for)

Now, based on that approach:
- The tasks page needs work, it's ok :p
- The host status probably doesn't belong in the first column (in-lieu of playbook status) because it's variable width unless we replace the current labels with icons and a number or something like the number of tags with the appropriate background color:
![Screenshot from 2022-08-04 20-33-06](https://user-images.githubusercontent.com/1291204/182977545-b62685bd-3ec7-41ad-bc94-187f0a86a48b.png)

- The playbook name (or path) could go after the host name, but then that pushes the host status further away
  - Would ``<report> <date> <duration> <hostname> <status> <playbook name> <host facts> `` work ?
  - If we can find a pretty implementation of fixed width status it could go earlier on in the row too.

**Comment by dmsimard** [comment]
> The playbook name (or path) could go after the host name, but then that pushes the host status further away
>     * Would `<report> <date> <duration> <hostname> <status> <playbook name> <host facts> ` work ?
>     * If we can find a pretty implementation of fixed width status it could go earlier on in the row too.

I was curious what that might look like and while it may not be perfect, I don't dislike it either: https://github.com/dmsimard/ara/commit/b717b7d7d152b3bbb31f2f56213c8de0d2625242
![Screenshot from 2022-08-04 23-36-05](https://user-images.githubusercontent.com/1291204/182996404-c37f7421-82c0-4c53-8537-14756b2304f3.png)

There is probably no need to print the entire words "OK", "CHANGED", etc, because they take up a lot of width real estate.
It's somewhat unfortunate that failed and unreachable have the same color -- we could fold them within the same pill:
![Screenshot from 2022-08-04 23-48-29](https://user-images.githubusercontent.com/1291204/182997688-d2a53db2-31d2-405d-8be4-6afd7c339d30.png)

**Comment by hille721** [comment]
> There is probably no need to print the entire words "OK", "CHANGED", etc, because they take up a lot of width real estate.
It's somewhat unfortunate that failed and unreachable have the same color

I'm kind of used to it, thus it looks weired for me now. But you are absolutely right. We don't need that and having the status directly at the begining is pretty cool. 

Just one thing: I would rename "Last update" to simple "Date".

**Comment by hille721** [comment]
Rebased my branch on top of your and added (https://github.com/hille721/ara/commit/39822080ab98b67e90bddf0b31fc6cfe95c593b6)

* playbook name filter
* playbook path filter

Also if you now click on a playbook name / path. It will be filtered for that. Quite cool I think because thus you can check, which hosts were running for specific playbook runs

![image](https://user-images.githubusercontent.com/38468371/183094427-a79843df-0fbe-4c22-aa79-6892fe160469.png)

![image](https://user-images.githubusercontent.com/38468371/183094527-09dcfbbe-7774-4c0d-960e-87ad3ad37f83.png)

**Comment by flowerysong** [comment]
> There is probably no need to print the entire words "OK", "CHANGED", etc, because they take up a lot of width real estate. It's somewhat unfortunate that failed and unreachable have the same color -- we could fold them within the same pill: ![Screenshot from 2022-08-04 23-48-29](https://user-images.githubusercontent.com/1291204/182997688-d2a53db2-31d2-405d-8be4-6afd7c339d30.png)

Relying on colour alone is not ideal for accessibility.

**Comment by dmsimard** [comment]
> Relying on colour alone is not ideal for accessibility.

@flowerysong I agree. That's why I feel it's important to keep the full labels (with their corresponding colors) in the search box and have HTML title/tooltip attributes on the pills such that additional information and context is available on mouse-over:
![Peek 2022-08-05 12-25](https://user-images.githubusercontent.com/1291204/183120411-a199d52b-2298-448a-af56-88a3a13f55d3.gif)

There are many other instances where HTML titles and tooltips are used.
I realize that if the UI/UX was good and intuitive enough, we may not need to do that but I would love it if ara could have a skilled frontend contributor in the future, we could use the help :p

**Comment by dmsimard** [comment]
@hille721 I added a comment on your commit -- could you open a PR? Would make it easier to review and discuss.

**Comment by dmsimard** [comment]
If we go with the status pill implementation, I wonder whether we should only print the statuses for which we have something, not unlike what we had before, in fact.

It would look like this:
![Screenshot from 2022-08-05 12-36-15](https://user-images.githubusercontent.com/1291204/183121995-bf43e2ff-d1f3-4a4c-8b98-40f86a60d323.png)

The width becomes somewhat variable but I believe it makes it easier for users to scan for what they're looking for instead of having orange/red/blue everywhere.

**Comment by hille721** [comment]
> The width becomes somewhat variable but I believe it makes it easier for users to scan for what they're looking for instead of having orange/red/blue everywhere.

Agree, thought the same.

**Comment by dmsimard** [comment]
I'll close this now that the corresponding PR has landed. It's been a worthwhile iterative improvement. Thanks!
