### ISSUE TITLE
Log the username on the controller

### ISSUE THREAD

**Issue by widhalmt** [ansible-community/ara#415]
Hi,

First, thanks for Ara! We are working a lot with Ansible and this seems to fix not one but several issues we had in different setups.

One I'm still thinking about how to fix it with Ara is that we need to know *who* started a run of `ansible-playbook` in one project. If there was a convenient solution Ara would be perfect for us.

Here's the outline of what I'm talking about: We are working with a another team in a common cloud infrastructure. So there's their users as well as our users working on the same bastion host. Everyone has a local copy of common Ansible code (including playbooks, `ansible.cfg`, inventory etc.) in their home on the bastion host. When we change something, we change it in our local copy and contribute into common git repositories. These repositories are then checked out on a similar bastion host in another cloud environment for production. So we know exactly who changed what when in the Ansible code. But we do not know, who ran which playbook in production.

For documentation reasons we want to know who changed when what in production, in other words, who ran which playbook with what result in production. Ara is perfect for that, the only thing I can't find is the information of the user on the Ansible controller who started the playbook. My workaround would be to put it into `default_labels` but I hope there's a better one.

 Just to make it clear: This not about a full blown auditing solution. Yes, that would also be welcome but I guess that would be beyond the scope of this feature request. A prominent information about the username / Gecos of who started a run on the controller would be totally sufficient.

**Comment by dmsimard** [comment]
Hi @widhalmt and thanks for the issue.

This is a reasonable request, the use case makes sense and it's not too complicated to implement -- I think that makes it a good candidate for someone to contribute the feature :)

We already log the controller hostname/fqdn and I guess adding support for saving the user wouldn't be too different from that.
That feature was added in [this commit](https://github.com/ansible-community/ara/commit/52b201dae2c99f3f9b5fd015a7e3a81f81ed5440) to give you an idea of the necessary changes in the database model (and migration), the API, the UI, the CLI, the tests and the docs, as appropriate.

In the meantime, there's host facts that provide the [remote user](https://demo.recordsansible.org/hosts/10381.html#ansible_user_id) and maybe [ara_record](https://ara.readthedocs.io/en/latest/ansible-plugins-and-use-cases.html#ara-record-arbitrary-key-values-in-playbook-reports) can provide part of the solution too -- but instead of the example that records the git version, it records the current user. It doesn't easily allow to search based on the values (unless you manually iterate over them) but it's something.

In addition to default_labels, there's ara_playbook_labels that can be set as an extra var so maybe you could set that dynamically via a shell alias and the $USER variable.

**Comment by widhalmt** [comment]
Hi,

Thanks for the nice reply. I'm not big in Python. I'll ask around if I can find someone to help with it in our organization.

**Comment by widhalmt** [comment]
Just a short update: Looking good. The project is already forked and we're planning on making a PR with the changes we need.
