### ISSUE TITLE
Ara behind Caddy reverse proxy with authentication.

### ISSUE THREAD

**Issue by hialvaro** [ansible-community/ara#476]
## What is the issue ?

I have set up ARA with Caddy v2 as a reverse proxy, which is running perfectly. But when I activate the basicauth, it gets stuck in a loop where, after introducing the correct auth credentials, it asks for the authentication yet again. I have tested with other services to confirm it is not a Caddy issue, as it works well twith other services. Also, ARA is getting the request yet it returs a 401 response every time.

## What should be happening ?

Be able to simply log in and get to the ARA UI.

**Comment by dmsimard** [comment]
Hi @hialvaro,

Did you close the issue because you identified the problem ?

Would you like to explain briefly what it was in case someone else has a similar issue ?

![wisdom_of_the_ancients](https://user-images.githubusercontent.com/1291204/215191828-e5c65bd6-69af-402c-8d23-00acb0ba3534.png)

Thanks!
