### ISSUE TITLE
ara_default callback unable to load, disabled for FIPS

### ISSUE THREAD

**Issue by ttbigc** [ansible-community/ara#482]
I am trying to install ara in my Redhat 8 environment where we have FIPs enabled on all systems.
After installing the pip module and exporting the callback path, I get the following error when I run ansible-playbook:
Operations to perform:
  Apply all migrations: admin, api, auth, contenttypes, db, sessions
Running migrations:
  Applying contenttypes.0001_initial...[WARNING]: Skipping callback 'ara_default', unable to load due to: [digital envelope routines: EVP_DigestInit_ex] disabled for FIPS

Is there a workaround for this or is only option at this time to disable FIPs?

**Comment by flowerysong** [comment]
Duplicate of #280 

This looks like it is probably related to https://github.com/django/django/pull/14763, which was merged in for Django 4.1.

ara uses LTS versions of Django so it's currently on 3.2; 4.2 is due to be released in April, at which point we could look at upgrading.

There are workarounds you could try to implement on your own (e.g. updating to Django 4.1, or Google "django fips monkeypatch"), but not really anything suitable for the ara package.

**Comment by ttbigc** [comment]
Thanks for quick response @flowerysong. Closing as I will use monkey patch for Django.

**Comment by dmsimard** [comment]
This is accurate.

Thank you @flowerysong !
