### ISSUE TITLE
A non-django way of modifying settings.py

### ISSUE THREAD

**Issue by alainchiasson-guavus** [ansible-community/ara#53]
While we can modify settings.py through a module on the python path ( as described : https://docs.djangoproject.com/en/dev/topics/settings/), I don't beleive ARA is aimed as standalone server (that happens to use Django).

Would it make sense to have a CLI or ENV variable type configuration that is more "simplistic". Or if there is and I missed it?  point it out.

I encountered this while trying to create separate server and client - I needed to provide ALLOWED_HOSTS. While possible, I felt this was alot of python configuration ( not code ) that had to be understood.

**Comment by dmsimard** [comment]
@alainchiasson-guavus the [API configuration docs](https://ara.readthedocs.io/en/latest/api-configuration.html) specify what environment variables to use and what might otherwise be the configuration that will be read from ``~/.ara/server/settings.yaml`` by default.

The location of the settings file can be customized with ``ARA_SETTINGS``.

**Comment by dmsimard** [comment]
@alainchiasson, @alainchiasson-guavus -- I'll close this issue assuming your question was answered.
Please hop on IRC or Slack if you have any questions.

Thanks !
